name: Pipeline
on: 
  push:
  workflow_dispatch:
  
jobs:
  printAny:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | sort

      - run:  echo ${{ secrets.SECRET_FROM_ACTION_SECRETS }}
      - run: echo ${{ secrets.ENVIRONMENT }}      
      
  Pipeline:
    uses: defaultbr/cicd-base/.github/workflows/container-on-kubernetes.yaml@main

    with:
      username: "Oi CI"
  
