name: Pipeline
on: 
  push:
  workflow_dispatch:
  
jobs:
  printAny:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | sort
      
  Pipeline:
    uses: defaultbr/cicd-base/.github/workflows/container-on-kubernetes.yaml@main
    secrets:
      SECRET_FROM_ACTION_SECRETS: ${{ secrets.SECRET_FROM_ACTION_SECRETS }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
    with:
      username: "Oi CI"
  
