name: Pipeline
on: 
  push:
  workflow_dispatch:
  
jobs:
  printAny:
    runs-on: ubuntu-latest
    environment: homologation
    steps:
      - run: printenv | sort
      - run: echo SECRET_FROM_ACTION_SECRET ${{ secrets.SECRET_FROM_ACTION_SECRETS }}
      - run: echo Environment => ${{ secrets.ENVIRONMENT }}    
      - run: |
          if [[ "$ENVIRONMENT" == "homologation" ]]; then
            echo "É Homologation"
          elif [[ "$ENVIRONMENT" == "production"]]; then
            echo "É production"
          else
              echo "Nenhum ambiente"
          fi          
      
  Pipeline:
    uses: defaultbr/cicd-base/.github/workflows/container-on-kubernetes.yaml@main

    with:
      username: "Oi CI"
  
