name: hello-world
on: push
jobs:
  my-job:
    - uses: defaultbr/cicd-base/pipelines/container/k8s/workflow.yaml
# - uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
        
        
