name: Pipeline
on: 
  push:
  workflow_dispatch:
  
jobs:
  CI:
    uses: defaultbr/cicd-base/.github/workflows/container-on-kubernetes-CI.yaml@main
    with:
      username: "Oi CI"
      
  CD:
    uses: defaultbr/cicd-base/.github/workflows/container-on-kubernetes-CD.yaml@main
    with:
      username: "Oi CD"
