name: hello-world
on: 
  workflow_dispatch:
  
jobs:
  doIt:
    runs-on: ubuntu-latest
    steps:
      - run: echo "doit"
      
  
  hello:
    uses: defaultbr/cicd-base/.github/workflows/container-on-k8s.yaml@main
    with:
      username: "Oi 2"
        
