name: hello-world
on: 
  push:
  workflow_dispatch:
  
jobs:
  PIPELINE:
    uses: defaultbr/cicd-base/.github/workflows/container-on-k8s.yaml@main
    with:
      username: "Oi 2"
        
#   doIt:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "doit"
